Mgate_formations_index_admin:
    path:  /formations/admin
    defaults: { _controller: MgateFormationBundle:Formation:index}
    methods:  [GET, HEAD]

Mgate_formations_lister:
    path:  /formations
    defaults: { _controller: MgateFormationBundle:Formation:lister}
    methods:  [GET, HEAD]

Mgate_formation_voir:
    path:  /formations/{id}
    defaults: { _controller: MgateFormationBundle:Formation:voir }
    requirements:
        id: \d+
    methods:  [GET, HEAD]

Mgate_formation_ajouter:
    path:  /formations/admin/ajouter
    defaults: { _controller: MgateFormationBundle:Formation:ajouter }
    methods:  [GET, HEAD, POST]

Mgate_formation_modifier:
    path:  /formations/admin/modifier/{id}
    defaults: { _controller: MgateFormationBundle:Formation:modifier }
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]

Mgate_formation_supprimer:
    path:  /formations/admin/supprimer/{id}
    defaults: { _controller: MgateFormationBundle:Formation:supprimer }
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]

Mgate_formation_participation:
    path:  /formations/admin/participation/{mandat}
    defaults: { _controller: MgateFormationBundle:Formation:participation, mandat: null }
    methods:  [GET, HEAD]
