mgate_formations_index_admin:
    path:  /admin/formations
    defaults: { _controller: mgateFormationBundle:Formation:index}

mgate_formations_lister:
    path:  /formations
    defaults: { _controller: mgateFormationBundle:Formation:lister}

mgate_formation_voir:
    path:  /formations/{id}
    defaults: { _controller: mgateFormationBundle:Formation:voir }
    requirements:
        id: \d+

mgate_formation_ajouter:
    path:  /admin/formations/ajouter
    defaults: { _controller: mgateFormationBundle:Formation:modifier, id : -1}

mgate_formation_modifier:
    path:  /admin/formations/modifier/{id}
    defaults: { _controller: mgateFormationBundle:Formation:modifier }
    requirements:
        id: \d+

mgate_formation_supprimer:
    path:  /admin/formations/supprimer/{id}
    defaults: { _controller: mgateFormationBundle:Formation:supprimer }
    requirements:
        id: \d+

mgate_formation_participation:
    path:  /admin/formations/participation
    defaults: { _controller: mgateFormationBundle:Formation:participation }
