os: linux
dist: focal
language: ruby # travis default, no impact, removes warning at validation

services:
    - docker

script:
    - cp docker-compose.yml.dist docker-compose.yml
    - cp .env.dist .env
    - cp var/key_value_store/config.json.dist var/key_value_store/config.json
    - sed -i "s/REPLACE_WITH_YOUR_EMAIL/jeyser-crm.travis@example.com/g" docker-compose.yml .env
    - docker-compose build
    # check prod env is working
    - docker-compose up -d
    - sleep 10 && docker-compose run --rm web php bin/console cache:clear -e prod --no-warmup
    - docker-compose run --rm web composer install:first
    - docker-compose run --rm web php bin/console doctrine:schema:validate --ansi
    # Run tests on test env
    - docker-compose run --rm -e "APP_ENV=dev" web bash -c "composer install && php -d memory_limit=1024M vendor/bin/behat ./features/"
    - docker-compose stop


