sudo: required

services:
    - docker

script:
    - cp docker-compose.yml.dist docker-compose.yml
    - docker-compose build
#    - docker-compose run --rm web composer install -o -n
    - docker-compose run --rm web php bin/console cache:clear -e=test
    - docker-compose run --rm web vendor/bin/behat ./features/ -f pretty
    - docker-compose stop
