sudo: required

services:
    - docker

script:
    - cp docker-compose.yml.dist docker-compose.yml
    - docker-compose build
    - docker-compose up -d
#    - docker-compose run --rm web composer install -o -n
    - sleep 10 && docker-compose run --rm web php bin/console cache:clear -e=test
    - docker-compose run --rm web php bin/console doctrine:schema:validate --ansi
#    - docker-compose run --rm web vendor/bin/behat ./features/ -f pretty
    - docker-compose stop
