# Domaines de compétence ######################################################

MgateSuivi_domaine_index:
    path: /DomainesDeCompetence
    defaults: {_controller: MgateSuiviBundle:DomaineCompetence:index }
    methods:  [GET, HEAD, POST]

MgateSuivi_domaine_delete:
    path: /DomainesDeCompetence/Supprimer/{id}
    defaults: {_controller: MgateSuiviBundle:DomaineCompetence:delete }
    requirements:
      id : \d+
    methods:  [GET, HEAD, POST]

###############################################################################

MgateSuivi_vu_ca:
    path:  /ca/{id}
    defaults: {_controller: MgateSuiviBundle:Etude:vuCA, id:-1 }
    methods:  [GET, HEAD]

MgateSuivi_etude_homepage:
    path:  /
    defaults: {_controller: MgateSuiviBundle:Etude:index}
    methods:  [GET, HEAD]

MgateSuivi_etude_ajax:
    path:  /get
    defaults: {_controller: MgateSuiviBundle:Etude:getEtudesAsync}
    methods:  [GET, HEAD]

MgateSuivi_etude_suivi:
    path: /etudes/suivi
    defaults: {_controller: MgateSuiviBundle:Etude:suivi}
    methods:  [GET, HEAD]

MgateSuivi_etude_suiviQualite:
    path: /etudes/suiviQualite
    defaults: {_controller: MgateSuiviBundle:Etude:suiviQualite}
    methods:  [GET, HEAD]

MgateSuivi_etude_ajouter:
    path: /etude/ajouter
    defaults: {_controller: MgateSuiviBundle:Etude:add}
    methods:  [GET, HEAD, POST]

MgateSuivi_etude_voir:
    path:   /etude/{nom}
    defaults: {_controller: MgateSuiviBundle:Etude:voir}
    requirements:
        numero:  \d+
    methods:  [GET, HEAD]

MgateSuivi_etude_modifier:
    path: /etude/modifier/{nom}
    defaults: {_controller: MgateSuiviBundle:Etude:modifier}
    requirements:
        numero:  \d+
    methods:  [GET, HEAD, POST]

MgateSuivi_etude_supprimer:
    path: /etude/supprimer/{nom}
    defaults: {_controller: MgateSuiviBundle:Etude:delete}
    requirements:
        numero: \d+
    methods:  [GET, HEAD, POST]

MgateSuivi_ap_rediger:
    path: /ap/rediger/{id}
    defaults: {_controller: MgateSuiviBundle:Ap:rediger}
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]

MgateSuivi_ap_suivi:
    path: /ap/suivi/{id}
    defaults: {_controller: MgateSuiviBundle:Ap:suivi}
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]

MgateSuivi_cc_rediger:
    path: /cc/rediger/{id}
    defaults: {_controller: MgateSuiviBundle:Cc:rediger}
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]

MgateSuivi_missions_modifier:
    path: /missions/modifier/{id}
    defaults: {_controller: MgateSuiviBundle:Missions:modifier}
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]

#AJOUT AJAX

MgateSuivi_mission_avancement:
    path: /missions/modifier/avancement/
    defaults: {_controller: MgateSuiviBundle:Mission:avancement}
    methods:  [POST]

MgateSuivi_state:
    path: /suivi/state/
    defaults: {_controller: MgateSuiviBundle:Etude:state}
    methods:  [POST]

#MgateSuivi_missions_repartition:
#    path: /missions/repartition/{id}
#    defaults: {_controller: MgateSuiviBundle:MissionsRepartition:index}
#    requirements:
#        id: \d+


MgateSuivi_clientcontact_ajouter:
    path: /clientcontact/ajouter/{id}
    defaults: {_controller: MgateSuiviBundle:ClientContact:add}
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]

MgateSuivi_clientcontact_modifier:
    path: /clientcontact/modifier/{id}
    defaults: {_controller: MgateSuiviBundle:ClientContact:modifier}
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]

MgateSuivi_clientcontact_voir:
    path: /clientcontact/voir/{id}
    defaults: {_controller: MgateSuiviBundle:ClientContact:voir}
    requirements:
        id: \d+
    methods:  [GET, HEAD]

MgateSuivi_clientcontact_index:
    path: /clientcontact/
    defaults: {_controller: MgateSuiviBundle:ClientContact:index}
    methods:  [GET, HEAD]


MgateSuivi_suivi_ajouter:
    path: /suivi/ajouter/{id}
    defaults: {_controller: MgateSuiviBundle:Suivi:add}
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]

MgateSuivi_suivi_modifier:
    path: /suivi/modifier/{id}
    defaults: {_controller: MgateSuiviBundle:Suivi:modifier}
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]

MgateSuivi_suivi_voir:
    path: /suivi/voir/{id}
    defaults: {_controller: MgateSuiviBundle:Suivi:voir}
    requirements:
        id: \d+
    methods:  [GET, HEAD]

MgateSuivi_suivi_index:
    path: /suivi
    defaults: {_controller: MgateSuiviBundle:Suivi:index}
    methods:  [GET, HEAD]


MgateSuivi_av_ajouter:
    path: /av/ajouter/{id}
    defaults: {_controller: MgateSuiviBundle:Av:add}
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]

MgateSuivi_av_modifier:
    path: /av/modifier/{id}
    defaults: {_controller: MgateSuiviBundle:Av:modifier}
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]

MgateSuivi_av_voir:
    path: /av/voir/{id}
    defaults: {_controller: MgateSuiviBundle:Av:voir}
    requirements:
        id: \d+
    methods:  [GET, HEAD]

MgateSuivi_avmission_ajouter:
    path: /avmission/ajouter/{id}
    defaults: {_controller: MgateSuiviBundle:AvMission:add}
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]


MgateSuivi_avmission_voir:
    path: /avmission/voir/{id}
    defaults: {_controller: MgateSuiviBundle:AvMission:voir}
    requirements:
        id: \d+
    methods:  [GET, HEAD]


MgateSuivi_avmission_modifier:
    path: /avmission/modifier/{id}
    defaults: {_controller: MgateSuiviBundle:AvMission:modifier}
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]

MgateSuivi_phases_modifier:
    path: /phases/modifier/{id}
    defaults: {_controller: MgateSuiviBundle:Phases:modifier}
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]

MgateSuivi_procesverbal_ajouter:
    path: /procesverbal/ajouter/{id}
    defaults: {_controller: MgateSuiviBundle:ProcesVerbal:add}
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]

MgateSuivi_procesverbal_modifier:
    path: /procesverbal/modifier/{id}
    defaults: {_controller: MgateSuiviBundle:ProcesVerbal:modifier}
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]

MgateSuivi_procesverbal_rediger:
    path: /procesverbal/rediger/{id}/{type}
    defaults: {_controller: MgateSuiviBundle:ProcesVerbal:rediger}
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]

MgateSuivi_procesverbal_supprimer:
    path: /procesverbal/supprimer/{id}
    defaults: {_controller: MgateSuiviBundle:ProcesVerbal:delete}
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]

MgateSuivi_etude_suivi_update:
    path:  /suivi/update/{id}
    defaults: { _controller: MgateSuiviBundle:Etude:suiviUpdate }
    methods:  [POST]
    methods:  [POST]


MgateSuivi_groupes_modifier:
    path: /groupes/modifier/{id}
    defaults: {_controller: MgateSuiviBundle:GroupePhases:modifier}
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]
