mgate_indicateurs_index:
    path:  /admin/indicateurs
    defaults: { _controller: mgateStatBundle:Indicateurs:index }

mgate_indicateurs_ajax_suivi:
    path:  /admin/indicateurs/etudes
    defaults: { _controller: mgateStatBundle:Indicateurs:ajax }

mgate_indicateurs_debug:
    path:  /admin/indicateurs/{get}
    defaults: { _controller: mgateStatBundle:Indicateurs:debug}
