parameters:
#    mgate_stat.example.class: mgate\StatBundle\Example
     mgate_stat.chart_factory.class: mgate\StatBundle\Manager\ChartFactory

services:
#    mgate_stat.example:
#        class: %mgate_stat.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    mgate_stat.chart_factory:
        class: "%mgate_stat.chart_factory.class%"
        arguments: []
