mgate_user_lister:
    path:  /user/lister
    defaults: { _controller: mgateUserBundle:Default:lister }
    methods:  [GET, HEAD]


mgate_user_voir:
    path:  /user/voir/{id}
    defaults: { _controller: mgateUserBundle:Default:voir }
    methods:  [GET, HEAD]

mgate_user_modifier:
    path:  /user/modifier/{id}
    defaults: { _controller: mgateUserBundle:Default:modifier }
    methods:  [GET, HEAD, POST]

mgate_user_supprimer:
    path:  /user/supprimer/{id}
    defaults: { _controller: mgateUserBundle:Default:delete }
    methods:  [GET, HEAD, POST]


mgate_user_addFromPersonne:
    path: /user/addFromPersonne/{id}
    defaults: { _controller: mgateUserBundle:Default:addUserFromPersonne }
    methods:  [GET, HEAD, POST]

