parameters:
    mgate.conversionlettre.class: mgate\PubliBundle\Manager\ConversionLettreFormatter
    mgate.twigextentionmanager.class: mgate\PubliBundle\Manager\TwigExtensionManager
    mgate.document_manager.class: mgate\PubliBundle\Manager\DocumentManager


services:
    mgate.conversionlettre:
        class: "%mgate.conversionlettre.class%"
    twig.stringloader:
        class: Twig_Loader_String
        tags:
            - { name: twig.loader }
    mgate.twig_extension:
        class: "%mgate.twigextentionmanager.class%"
        tags:
            - { name: twig.extension }
    mgate.document_manager:
        class: "%mgate.document_manager.class%"
        arguments:
            em : "@doctrine.orm.entity_manager"
            container : "@service_container"
            securityContext : "@security.context"
