parameters:
    Mgate.conversionlettre.class: Mgate\PubliBundle\Manager\ConversionLettreFormatter
    Mgate.twigextentionmanager.class: Mgate\PubliBundle\Manager\TwigExtensionManager
    Mgate.document_manager.class: Mgate\PubliBundle\Manager\DocumentManager


services:
    Mgate.conversionlettre:
        class: "%Mgate.conversionlettre.class%"
    twig.stringloader:
        class: Twig_Loader_String
        tags:
            - { name: twig.loader }
    Mgate.twig_extension:
        class: "%Mgate.twigextentionmanager.class%"
        tags:
            - { name: twig.extension }
    Mgate.document_manager:
        class: "%Mgate.document_manager.class%"
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%junior_id%"
            - "%junior_authorizedStorageSize%"
            - "@security.token_storage"
            - "@kernel"

    Mgate.import.siaje_etude:
            class:  Mgate\PubliBundle\Manager\SiajeEtudeImporter
            arguments: [ "@doctrine.orm.entity_manager" ]
