<?php

namespace App\Repository\Booking;

use Doctrine\ORM\EntityRepository;
use DateTime;

/**
 * BookingRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingRepository extends EntityRepository
{
  public function getBookings(DateTime $start, DateTime $end)
  {
    $qb = $this-> _em->createQueryBuilder('booking');
    $query = $qb
      ->where('booking.beginAt BETWEEN :start and :end OR booking.endAt BETWEEN :start and :end')
      ->setParameter('start', $start->format('Y-m-d H:i:s'))
      ->setParameter('end', $end->format('Y-m-d H:i:s'));

    return $query->getQuery()->getResult();
  }
}
