mgatePersonne_listeDiffusion:
    path: /listediffusion
    defaults: { _controller: mgatePersonneBundle:Personne:listeMail }
    methods:  [GET, HEAD]

mgatePersonne_personne_supprimer:
    path: /personne/supprimer/{id}
    defaults: {_controller: mgatePersonneBundle:Personne:delete}
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]

mgatePersonne_annuaire:
    path: /annuaire
    defaults: { _controller: mgatePersonneBundle:Personne:annuaire }
    methods:  [GET, HEAD]

mgatePersonne_homepage:
    path:  /
    defaults: { _controller: mgatePersonneBundle:Default:index }
    methods:  [GET, HEAD]

mgatePersonne_prospect_homepage:
    path:  /prospect/{page}
    defaults: { _controller: mgatePersonneBundle:Prospect:index , page: 1 }
    requirements:
      page : \d*
    methods:  [GET, HEAD]

mgatePersonne_prospect_ajouter:
    path: /prospect/add/{format}
    defaults: {_controller: mgatePersonneBundle:Prospect:ajouter, format:null}
    methods:  [GET, HEAD, POST]

mgatePersonne_prospect_voir:
    path:   /prospect/voir/{id}
    defaults:  { _controller: mgatePersonneBundle:Prospect:voir}
    requirements:
        id:  \d+
    methods:  [GET, HEAD]

mgatePersonne_prospect_modifier:
    path: /prospect/modifier/{id}
    defaults: {_controller: mgatePersonneBundle:Prospect:modifier}
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]

mgatePersonne_prospect_supprimer:
    path: /prospect/supprimer/{id}
    defaults: {_controller: mgatePersonneBundle:Prospect:delete}
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]

mgatePersonne_employe_homepage:
    path:  /employe
    defaults: { _controller: mgatePersonneBundle:Employe:index , page: 1 }
    requirements:
      page : \d*
    methods:  [GET, HEAD]


mgatePersonne_employe_ajouter:
    path: /employe/add/{prospect_id}/{format}
    defaults: {_controller: mgatePersonneBundle:Employe:ajouter, format:null}
    requirements:
        prospect_id: \d+
    methods:  [GET, HEAD, POST]

mgatePersonne_employe_voir:
    path:   /employe/{id}
    defaults:  { _controller: mgatePersonneBundle:Employe:voir}
    requirements:
        id:  \d+
    methods:  [GET, HEAD]

mgatePersonne_employe_modifier:
    path: /employe/modifier/{id}
    defaults: {_controller: mgatePersonneBundle:Employe:modifier}
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]

mgatePersonne_intervenants_homepage:
    path:  /intervenants
    defaults: { _controller: mgatePersonneBundle:Membre:listIntervenants }
    methods:  [GET, HEAD]

mgatePersonne_membre_homepage:
    path:  /membre
    defaults: { _controller: mgatePersonneBundle:Membre:index }
    methods:  [GET, HEAD]

mgatePersonne_membre_ajouter:
    path: /membre/add
    defaults: {_controller: mgatePersonneBundle:Membre:modifier, id:0}
    methods:  [GET, HEAD, POST]

mgatePersonne_membre_voir:
    path:   /membre/{id}
    defaults:  { _controller: mgatePersonneBundle:Membre:voir}
    requirements:
        id:  \d+
    methods:  [GET, HEAD]

mgatePersonne_membre_impayes:
    path:  /membre/impayes
    defaults: { _controller: mgatePersonneBundle:Membre:impayes }
    methods:  [GET, HEAD]

mgatePersonne_membre_modifier:
    path: /membre/modifier/{id}
    defaults: {_controller: mgatePersonneBundle:Membre:modifier}
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]

mgatePersonne_membre_supprimer:
    path: /membre/supprimer/{id}
    defaults: {_controller: mgatePersonneBundle:Membre:delete}
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]

mgatePersonne_poste_homepage:
    path:  /poste
    defaults: { _controller: mgatePersonneBundle:Poste:index , page: 1 }
    requirements:
      page : \d*
    methods:  [GET, HEAD]

mgatePersonne_poste_ajouter:
    path: /poste/add
    defaults: {_controller: mgatePersonneBundle:Poste:ajouter}
    methods:  [GET, HEAD, POST]

mgatePersonne_poste_voir:
    path:   /poste/{id}
    defaults:  { _controller: mgatePersonneBundle:Poste:voir}
    requirements:
        id:  \d+
    methods:  [GET, HEAD]

mgatePersonne_poste_modifier:
    path: /poste/modifier/{id}
    defaults: {_controller: mgatePersonneBundle:Poste:modifier}
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]

mgatePersonne_poste_supprimer:
    path: /poste/supprimer/{id}
    defaults: {_controller: mgatePersonneBundle:Poste:delete}
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]

mgatePersonne_ajax_employes_de_prospect:
    path: /ajax/employes_de_prospect/{id}
    defaults: { _controller: mgatePersonneBundle:Prospect:ajaxEmployes}
    requirements:
        id: \d+
    methods: [GET, HEAD]
