MgatePersonne_listeDiffusion:
    path: /listediffusion
    defaults: { _controller: MgatePersonneBundle:Personne:listeMail }
    methods:  [GET, HEAD]

MgatePersonne_personne_supprimer:
    path: /personne/supprimer/{id}
    defaults: {_controller: MgatePersonneBundle:Personne:delete}
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]

MgatePersonne_annuaire:
    path: /annuaire
    defaults: { _controller: MgatePersonneBundle:Personne:annuaire }
    methods:  [GET, HEAD]

MgatePersonne_homepage:
    path:  /
    defaults: { _controller: MgatePersonneBundle:Default:index }
    methods:  [GET, HEAD]

MgatePersonne_prospect_homepage:
    path:  /prospect/
    defaults: { _controller: MgatePersonneBundle:Prospect:index }
    methods:  [GET, HEAD]

MgatePersonne_prospect_ajouter:
    path: /prospect/add/{format}
    defaults: {_controller: MgatePersonneBundle:Prospect:ajouter, format:null}
    methods:  [GET, HEAD, POST]

MgatePersonne_prospect_voir:
    path:   /prospect/voir/{id}
    defaults:  { _controller: MgatePersonneBundle:Prospect:voir}
    requirements:
        id:  \d+
    methods:  [GET, HEAD]

MgatePersonne_prospect_modifier:
    path: /prospect/modifier/{id}
    defaults: {_controller: MgatePersonneBundle:Prospect:modifier}
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]

MgatePersonne_prospect_supprimer:
    path: /prospect/supprimer/{id}
    defaults: {_controller: MgatePersonneBundle:Prospect:delete}
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]

MgatePersonne_employe_ajouter:
    path: /employe/add/{prospect_id}/{format}
    defaults: {_controller: MgatePersonneBundle:Employe:ajouter, format:null}
    requirements:
        prospect_id: \d+
    methods:  [GET, HEAD, POST]

MgatePersonne_employe_modifier:
    path: /employe/modifier/{id}
    defaults: {_controller: MgatePersonneBundle:Employe:modifier}
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]

MgatePersonne_employe_supprimer:
    path: /employe/supprimer/{id}
    defaults: {_controller: MgatePersonneBundle:Employe:delete}
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]

MgatePersonne_intervenants_homepage:
    path:  /intervenants
    defaults: { _controller: MgatePersonneBundle:Membre:listIntervenants }
    methods:  [GET, HEAD]

MgatePersonne_membre_homepage:
    path:  /membre
    defaults: { _controller: MgatePersonneBundle:Membre:index }
    methods:  [GET, HEAD]

MgatePersonne_membre_ajouter:
    path: /membre/add
    defaults: {_controller: MgatePersonneBundle:Membre:modifier, id:0}
    methods:  [GET, HEAD, POST]

MgatePersonne_membre_voir:
    path:   /membre/{id}
    defaults:  { _controller: MgatePersonneBundle:Membre:voir}
    requirements:
        id:  \d+
    methods:  [GET, HEAD]

MgatePersonne_membre_impayes:
    path:  /membre/impayes
    defaults: { _controller: MgatePersonneBundle:Membre:impayes }
    methods:  [GET, HEAD]

MgatePersonne_membre_modifier:
    path: /membre/modifier/{id}
    defaults: {_controller: MgatePersonneBundle:Membre:modifier}
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]

MgatePersonne_membre_supprimer:
    path: /membre/supprimer/{id}
    defaults: {_controller: MgatePersonneBundle:Membre:delete}
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]

MgatePersonne_poste_homepage:
    path:  /poste
    defaults: { _controller: MgatePersonneBundle:Poste:index }
    requirements:
      page : \d*
    methods:  [GET, HEAD]

MgatePersonne_poste_ajouter:
    path: /poste/add
    defaults: {_controller: MgatePersonneBundle:Poste:ajouter}
    methods:  [GET, HEAD, POST]

MgatePersonne_poste_modifier:
    path: /poste/modifier/{id}
    defaults: {_controller: MgatePersonneBundle:Poste:modifier}
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]

MgatePersonne_poste_supprimer:
    path: /poste/supprimer/{id}
    defaults: {_controller: MgatePersonneBundle:Poste:delete}
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]

MgatePersonne_filiere_ajouter:
    path: /filiere/add
    defaults: {_controller: MgatePersonneBundle:Filiere:ajouter}
    methods:  [GET, HEAD, POST]

MgatePersonne_filiere_modifier:
    path: /filiere/modifier/{id}
    defaults: {_controller: MgatePersonneBundle:Filiere:modifier}
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]

MgatePersonne_filiere_supprimer:
    path: /filiere/supprimer/{id}
    defaults: {_controller: MgatePersonneBundle:Filiere:delete}
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]

MgatePersonne_ajax_employes_de_prospect:
    path: /ajax/employes_de_prospect/{id}
    defaults: { _controller: MgatePersonneBundle:Prospect:ajaxEmployes}
    requirements:
        id: \d+
    methods: [GET, HEAD]

MgatePersonne_ajax_prospect:
    path: /ajax/ajax_prospect/
    defaults: { _controller: MgatePersonneBundle:Prospect:ajaxProspect}
    methods: [GET, HEAD]
