n7consultingDevco_homepage:
    path:     /
    defaults: { _controller: n7consultingDevcoBundle:Appel:index }


n7consultingDevco_appel_voir:
    path:   /appel/{id}
    defaults:  { _controller: n7consultingDevcoBundle:Appel:voir}
    requirements:
        id:  \d+
    methods:  [GET, HEAD]

n7consultingDevco_appel_ajouter:
    path: /appel/add
    defaults: {_controller: n7consultingDevcoBundle:Appel:ajouter}
    methods:  [GET, HEAD, POST]

n7consultingDevco_appel_modifier:
    path: /appel/modifier/{id}
    defaults: {_controller: n7consultingDevcoBundle:Appel:modifier}
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]

n7consultingDevco_appel_supprimer:
    path: /appel/supprimer/{id}
    defaults: {_controller: n7consultingDevcoBundle:Appel:delete}
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]
