Mgate_treso_urssaf:
    path:  /urssaf/{year}/{month}
    defaults: { _controller: MgateTresoBundle:Urssaf:index, year: null, month: null }
    methods:  [GET, HEAD, POST]


################################################################################
#                                                                              #
#                                DECLARATIFS                                   #
#                                                                              #
################################################################################

MgateTreso_Declaratif_index:
    path:  /Declaratifs
    defaults: { _controller: MgateTresoBundle:Declaratif:index }
    methods:  [GET, HEAD]


MgateTreso_Declaratif_TVA:
    path:  /Declaratifs/TVA/{year}/{month}/{trimestriel}
    defaults: { _controller: MgateTresoBundle:Declaratif:tva, year: null, month: null, trimestriel: false }
    methods:  [GET, HEAD, POST]


MgateTreso_Declaratif_BRC:
    path:  /Declaratifs/BRC/{year}/{month}
    defaults: { _controller: MgateTresoBundle:Declaratif:brc, year: null, month: null }
    methods:  [GET, HEAD, POST]

################################################################################
#                                                                              #
#                                  FACTURES                                    #
#                                                                              #
################################################################################

MgateTreso_Facture_index:
    path:  /Factures
    defaults: { _controller: MgateTresoBundle:Facture:index }
    methods:  [GET, HEAD]


MgateTreso_Facture_voir:
    path:  /Facture/{id}
    defaults: { _controller: MgateTresoBundle:Facture:voir }
    requirements:
        id: \d+
    methods:  [GET, HEAD]


MgateTreso_Facture_ajouter:
    path:  /Facture/Ajouter/{etude_id}
    defaults: { _controller: MgateTresoBundle:Facture:modifier,  id:-1 , etude_id:-1 }
    methods:  [GET, HEAD, POST]


MgateTreso_Facture_modifier:
    path:  /Facture/Modifier/{id}/{etude_id}
    defaults: { _controller: MgateTresoBundle:Facture:modifier, etude_id:-1 }
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]


MgateTreso_Facture_supprimer:
    path:  /Facture/Supprimer/{id}
    defaults: { _controller: MgateTresoBundle:Facture:supprimer }
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]


################################################################################
#                                                                              #
#                                NOTE DE FRAIS                                 #
#                                                                              #
################################################################################

MgateTreso_NoteDeFrais_index:
    path:  /NoteDeFrais
    defaults: { _controller: MgateTresoBundle:NoteDeFrais:index }
    methods:  [GET, HEAD]


MgateTreso_NoteDeFrais_voir:
    path:  /NoteDeFrais/{id}
    defaults: { _controller: MgateTresoBundle:NoteDeFrais:voir }
    requirements:
        id: \d+
    methods:  [GET, HEAD]


MgateTreso_NoteDeFrais_ajouter:
    path:  /NoteDeFrais/Ajouter
    defaults: { _controller: MgateTresoBundle:NoteDeFrais:modifier,  id:-1  }
    methods:  [GET, HEAD, POST]


MgateTreso_NoteDeFrais_modifier:
    path:  /NoteDeFrais/Modifier/{id}
    defaults: { _controller: MgateTresoBundle:NoteDeFrais:modifier }
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]


MgateTreso_NoteDeFrais_supprimer:
    path:  /NoteDeFrais/Supprimer/{id}
    defaults: { _controller: MgateTresoBundle:NoteDeFrais:supprimer }
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]


################################################################################
#                                                                              #
#                           BULLETIN DE VERSEMENT                              #
#                                                                              #
################################################################################
MgateTreso_BV_index:
    path:  /BV
    defaults: { _controller: MgateTresoBundle:BV:index }
    methods:  [GET, HEAD]


MgateTreso_BV_voir:
    path:  /BV/Voir/{id}
    defaults: { _controller: MgateTresoBundle:BV:voir }
    requirements:
        id: \d+
    methods:  [GET, HEAD]


MgateTreso_BV_ajouter:
    path:  /BV/Ajouter
    defaults: { _controller: MgateTresoBundle:BV:modifier,  id:-1  }
    methods:  [GET, HEAD, POST]


MgateTreso_BV_modifier:
    path:  /BV/Modifier/{id}
    defaults: { _controller: MgateTresoBundle:BV:modifier }
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]


MgateTreso_BV_supprimer:
    path:  /BV/Supprimer/{id}
    defaults: { _controller: MgateTresoBundle:BV:supprimer }
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]


################################################################################
#
#                               ADMINISTRATION
#
################################################################################

################################################################################
#                                                                              #
#                               COMPTES COMPTA                                 #
#                                                                              #
################################################################################

MgateTreso_Compte_index:
    path:  /Comptes
    defaults: { _controller: MgateTresoBundle:Compte:index }
    methods:  [GET, HEAD]

MgateTreso_Compte_ajouter:
    path:  /Compte/Ajouter
    defaults: { _controller: MgateTresoBundle:Compte:modifier,  id:-1, etude_id :-1  }
    methods:  [GET, HEAD, POST]

MgateTreso_Compte_modifier:
    path:  /Compte/Modifier/{id}
    defaults: { _controller: MgateTresoBundle:Compte:modifier }
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]

MgateTreso_Compte_supprimer:
    path:  /Compte/Supprimer/{id}
    defaults: { _controller: MgateTresoBundle:Compte:supprimer }
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]

################################################################################
#                                                                              #
#                                BASE URSSAF                                   #
#                                                                              #
################################################################################
MgateTreso_BaseURSSAF_index:
    path:  /BasesURSSAF
    defaults: { _controller: MgateTresoBundle:BaseURSSAF:index }
    methods:  [GET, HEAD]

MgateTreso_BaseURSSAF_ajouter:
    path:  /BaseURSSAF/Ajouter
    defaults: { _controller: MgateTresoBundle:BaseURSSAF:modifier,  id:-1  }
    methods:  [GET, HEAD, POST]

MgateTreso_BaseURSSAF_modifier:
    path:  /BaseURSSAF/Modifier/{id}
    defaults: { _controller: MgateTresoBundle:BaseURSSAF:modifier }
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]

MgateTreso_BaseURSSAF_supprimer:
    path:  /BaseURSSAF/Supprimer/{id}
    defaults: { _controller: MgateTresoBundle:BaseURSSAF:supprimer }
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]


################################################################################
#                                                                              #
#                              COTISATION URSSAF                               #
#                                                                              #
################################################################################

MgateTreso_CotisationURSSAF_index:
    path:  /CotisationsURSSAF
    defaults: { _controller: MgateTresoBundle:CotisationURSSAF:index }
    methods:  [GET, HEAD]

MgateTreso_CotisationURSSAF_ajouter:
    path:  /CotisationURSSAF/Ajouter
    defaults: { _controller: MgateTresoBundle:CotisationURSSAF:modifier,  id:-1  }
    methods:  [GET, HEAD, POST]

MgateTreso_CotisationURSSAF_modifier:
    path:  /CotisationURSSAF/Modifier/{id}
    defaults: { _controller: MgateTresoBundle:CotisationURSSAF:modifier }
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]

MgateTreso_CotisationURSSAF_supprimer:
    path:  /CotisationURSSAF/Supprimer/{id}
    defaults: { _controller: MgateTresoBundle:BV:supprimer }
    requirements:
        id: \d+
    methods:  [GET, HEAD, POST]
