<?php

/*
 * This file is part of the Incipio package.
 *
 * (c) Florian Lefevre
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Repository\Comment;

use App\Entity\Project\Etude;
use App\Entity\Comment\Comment;
use Doctrine\ORM\EntityRepository;
use App\Service\Comment\AbstractCommentManager;
use App\Service\Comment\CommentManagerInterface;

/**
 * commentRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function findAllByEtude(CommentManagerInterface $commentManager)
    {
        $qb = $this->_em->createQueryBuilder();
        $query = $qb->select('f')->from(Etude::class, 'f')
            ->orderBy('f.id', 'asc');
        $entities = $query->getQuery()->getResult();

        $date = new \DateTime('now' );
        $mois = $date->format('m');
        $annee = $date->format('Y');
        $jour = $date->format('d');

        $commentsParEtude = [];
        /** @var Comment $comment */
        foreach ($entities as $etude) {
            $nom = $etude->getNom();
            $thread = $etude->getThread();
            $comments = $commentManager->findCommentsByThread($thread); 
            foreach ($comments as $comment) { // Condition pour afficher que les commentaires des 10 derniers jours
                if (($comment->getCreatedAt()->format('m') >= $mois - 1) 
                && ($comment->getCreatedAt()->format('Y') == $annee )
                && $jour - $comment->getCreatedAt()->format('d') < 10) {
                    if (array_key_exists($nom, $commentsParEtude)) {
                        $commentsParEtude[$nom][] = $comment;
                    } else {
                        $commentsParEtude[$nom] = [$comment];
                    }
                }
            }
        }

        return $commentsParEtude;
    }
}
